const recipes = {
  meals: [
    {
      idMeal: "53262",
      strMeal: "Adana kebab",
      strMealAlternate: null,
      strCategory: "Lamb",
      strArea: "Turkish",
      strCountry: "Turkey",
      strInstructions: "step 1\r\nFinely chop the peppers in a food processor, then tip them in a sieve and press into the sieve so that the peppers release all of their juices. Tip into a bowl along with the mince, red pepper paste, pul biber, 1½ tsp flaky sea salt, and 2 tbsp of the oil. Mix together, kneading well for at least 2-3 mins. If you need to, wet your hands with cold water to prevent the mixture from sticking. The mixture should be sticky when ready. Cover and chill for at least 2 hrs, or up to 12 hrs.\r\n\r\nstep 2\r\nWhen ready to cook, heat the grill to high or an oven to 220C/200C fan/gas 6. Divide the mixture into 12 equal portions, around 85g each. If you’d like to skewer them, divide into 8 equal portions and roll into balls. Using wet hands, thread the balls onto the end of the skewers, massaging the mixture down the skewers in between the palms of your hands, until evenly distributed. Ensure that the mixture is fully wrapped tightly around the skewers without any exposed metal. Alternatively, lay them on a large baking tray lined with parchment paper if cooking in the oven, or foil if cooking under the grill. Shape into 20cm-long köfte. Wet your fingers with a little cold water and make indents all along the köfte for the traditional shape.\r\n\r\nstep 3\r\nGently brush each köfte with the remaining 1 tbsp oil and cook under the grill, on the top shelf for 10-12 mins, turning regularly, or cook in the oven for 16-18 mins, until crispy on the outside and juicy in the middle",
      strMealThumb: "https://www.themealdb.com/images/media/meals/04axct1763793018.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=Wj7sXu9B_ME",
      strIngredient1: "Romano Pepper",
      strIngredient2: "Lamb Mince",
      strIngredient3: "Red Pepper Paste",
      strIngredient4: "Pul Biber",
      strIngredient5: "Sunflower Oil",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 large",
      "strMeasure2": "800g",
      "strMeasure3": "3  tablespoons",
      "strMeasure4": "1 tablespoon",
      "strMeasure5": "3  tablespoons",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/adana-kebab",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-22 06:28:49"
    },
    {
      "idMeal": "53179",
      "strMeal": "Ham croquetas",
      "strMealAlternate": null,
      "strCategory": "Pork",
      "strArea": "Spanish",
      "strCountry": "Spain",
      "strInstructions": "step 1\r\nTo make the filling, heat the olive oil in a pan until it starts to shimmer. Add the leek and sauté until soft but not coloured. Stir in the ham with a wooden spoon, fry for 1 min, then stir in the flour and fry over a medium heat, stirring occasionally, until the mixture is golden but not burnt – this will take about 5 mins.\r\n\r\nstep 2\r\nMeanwhile, combine the stock and milk in a small pan and heat until steaming but not boiling. Season with a few scrapes of nutmeg. Gradually add the liquid, a few tbsp at a time, stirring constantly.\r\n\r\nstep 3\r\nOnce you’ve incorporated all the milk stock, continue to cook the filling over a medium heat for about 10 mins or until it thickens and leaves the sides of the pan when you stir it.\r\n\r\nstep 4\r\nSeason with black pepper, taste and adjust the salt if necessary – the ham can be very salty to start with. The filling is now done: it has to be really thick because you don’t want the croquetas to turn into pancakes.\r\n\r\nstep 5\r\nSmooth the mixture onto a baking tray (30 x 20cm is fine). Once it has stopped steaming, cover with cling film to stop it drying out. Leave to cool before putting it in the fridge for 1 hr.\r\n\r\nstep 6\r\nWhen you're ready for the next stage, line up three bowls: the first filled with the flour, the second with beaten egg and the third with breadcrumbs. Take the ham mixture out of the fridge. Put a little bit of olive oil on your hands to make it easier to roll the croquetas.\r\n\r\nstep 7\r\nRoll a spoonful of the mixture between your palms. The size and shape of the croquetas is up to you, but the easiest is a walnut-sized ball. Then begin coating as follows.\r\n\r\nstep 8\r\nDunk the croquetas into the flour – you want a dusting – followed by the egg, then the breadcrumbs. Put them on a tray and, when you’ve used up all the mixture, place in the fridge for 30 mins.\r\n\r\nstep 9\r\nIf you have a deep-fat fryer, heat the oil to 180C and fry for a couple of mins. If not, heat the oil in a deep, heavy-bottomed saucepan until it starts to shimmer. Then add 5-6 croquetas at a time and fry until golden all over. Once cooked, drain on kitchen paper and eat straight away.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/6dpa7m1763331105.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/shorts/nT8MGiWldHk",
      "strIngredient1": "Plain Flour",
      "strIngredient2": "Egg",
      "strIngredient3": "Breadcrumbs",
      "strIngredient4": "Sunflower Oil",
      "strIngredient5": "Extra Virgin Olive Oil",
      "strIngredient6": "Leek",
      "strIngredient7": "jamón ibérico",
      "strIngredient8": "Plain Flour",
      "strIngredient9": "Vegetable Stock",
      "strIngredient10": "Milk",
      "strIngredient11": "Nutmeg",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "75g",
      "strMeasure2": "2 large",
      "strMeasure3": "75g",
      "strMeasure4": "For frying",
      "strMeasure5": "4 tbsp",
      "strMeasure6": "1/2 ",
      "strMeasure7": "70g",
      "strMeasure8": "60g",
      "strMeasure9": "75 ml ",
      "strMeasure10": "330ml",
      "strMeasure11": "Grated",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/ham-croquetas",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-16 22:09:25"
    },
     {
      "idMeal": "52960",
      "strMeal": "Salmon Avocado Salad",
      "strMealAlternate": null,
      "strCategory": "Seafood",
      "strArea": "British",
      "strCountry": "United Kingdom",
      "strInstructions": "Season the salmon, then rub with oil. Mix the dressing ingredients together. Halve, stone, peel and slice the avocados. Halve and quarter the cucumber lengthways, then cut into slices. Divide salad, avocado and cucumber between four plates, then drizzle with half the dressing.\r\n\r\nHeat a non-stick pan. Add the salmon and fry for 3-4 mins on each side until crisp but still moist inside. Put a salmon fillet on top of each salad and drizzle over the remaining dressing. Serve warm.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1549542994.jpg",
      "strTags": "Paleo,Keto,LowCarbs,Salad,Alcoholic,Halloween,",
      "strYoutube": "https://www.youtube.com/watch?v=FJiu2S0Xap0",
      "strIngredient1": "Salmon",
      "strIngredient2": "Avocado",
      "strIngredient3": "Cucumber",
      "strIngredient4": "Spinach",
      "strIngredient5": "Mint",
      "strIngredient6": "Lime",
      "strIngredient7": "Honey",
      "strIngredient8": "Olive Oil",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "400g",
      "strMeasure2": "3",
      "strMeasure3": "1",
      "strMeasure4": "400g",
      "strMeasure5": "4 tbs",
      "strMeasure6": "zest and juice of 1",
      "strMeasure7": "2 tsp",
      "strMeasure8": "3 tbs",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/4521/salmon-avocado-and-cucumber-salad",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53247",
      "strMeal": "Sea bass with sizzled ginger, chilli & spring onions",
      "strMealAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Vietnamese",
      "strCountry": "Vietnam",
      "strInstructions": "step 1\r\nSeason 6 sea bass fillets with salt and pepper, then slash the skin 3 times.\r\n\r\nstep 2\r\nHeat a heavy-based frying pan and add 1 tbsp sunflower oil.\r\n\r\nstep 3\r\nOnce hot, fry the sea bass fillets, skin-side down, for 5 mins or until the skin is very crisp and golden. The fish will be almost cooked through.\r\n\r\nstep 4\r\nTurn over, cook for another 30 seconds - 1 minute, then transfer to a serving plate and keep warm. You’ll need to fry the sea bass fillets in 2 batches.\r\n\r\nstep 5\r\nHeat 2 tbsp sunflower oil, then fry the large knob of peeled ginger, cut into matchsticks, 3 thinly sliced garlic cloves and 3 thinly shredded red chillies for about 2 mins until golden.\r\n\r\nstep 6\r\nTake off the heat and toss in the bunch of shredded spring onions. Splash the fish with 1 tbsp soy sauce and spoon over the contents of the pan.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/tqd7s21763780609.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=xzDYKZl50FQ",
      "strIngredient1": "Sea Bass Fillets",
      "strIngredient2": "Sunflower Oil",
      "strIngredient3": "Ginger",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Red Chilli",
      "strIngredient6": "Spring Onions",
      "strIngredient7": "Soy Sauce",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "6",
      "strMeasure2": "3  tablespoons",
      "strMeasure3": "Knob",
      "strMeasure4": "3 sliced thinly",
      "strMeasure5": "3 Large",
      "strMeasure6": "Bunch",
      "strMeasure7": "1 tablespoon",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/sea-bass-sizzled-ginger-chilli-spring-onions",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-22 03:00:58"
    },
    {
      "idMeal": "53373",
      "strMeal": "Air Fryer Egg Rolls",
      "strMealAlternate": null,
      "strCategory": "Side",
      "strArea": "Chinese",
      "strCountry": "China",
      "strInstructions": "Alternative Pan Fry Method: If you don’t have access to an air fryer, you can make these egg rolls using a traditional pan fry method. Add enough oil to a medium skillet with high walls so the oil is about 1/2 inch up the side of the skillet. Heat oil on medium high heat until it reaches 350°F. Add egg rolls and fry for 3 to 4 minutes, flip, and fry for another 3 to 4 minutes until golden brown. Remove and let them drain and cool on a few paper towels.\r\n\r\nCook the filling:\r\nIn a large skillet over medium heat, add the olive oil along with the ground pork or chicken. Break apart the meat with a spatula or wooden spoon as it cooks. Cook until the meat is cooked through, 6 to 8 minutes.\r\n\r\nAdd garlic, ginger, carrot, scallions, and cabbage. Continue to cook until cabbage wilts down and is soft, another 3 to 4 minutes, stirring regularly. Season the filling with soy sauce and rice wine vinegar, and take off the heat to cool. (This filling can be made in advance.)\r\n\r\nAssemble the egg rolls:\r\nPlace a single egg roll wrapper on a dry surface with one point of the square facing you (like a diamond). Place about 1/4 cup of the egg roll filling mixture in the middle of the wrapper.\r\n\r\nDip your fingers in water and run around the edges of the wrapper. Then fold the edges of the wrapper over the center and start rolling the egg roll away from you to form a tight cylinder. Place on a plate and repeat until you are out of filling. You should get at least a dozen egg rolls.\r\n\r\nAir fry the egg rolls:\r\nPlace the egg rolls in the basket of your air fryer. Spray or brush them lightly with oil. Add as many as you can without stacking the egg rolls, making sure they don’t touch. Air needs to circulate around them. Brush the egg rolls lightly with oil.\r\n\r\nPlace the basket in the air fryer and turn the air fryer to 350°F. Cook for 6 to 7 minutes, then flip the egg rolls, spray or brush with oil a second time on the bottom side, and cook for another 4 to 5 minutes.\r\n\r\nFinished egg rolls should be golden brown and crispy! Serve immediately.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/grhn401765687086.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=XnA-wcVb4l0",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Ground Pork",
      "strIngredient3": "Garlic",
      "strIngredient4": "Ginger",
      "strIngredient5": "Carrots",
      "strIngredient6": "Scallions",
      "strIngredient7": "Cabbage",
      "strIngredient8": "Soy Sauce",
      "strIngredient9": "Rice Vinegar",
      "strIngredient10": "Egg Roll Wrappers",
      "strIngredient11": "Oil",
      "strIngredient12": "Duck Sauce",
      "strIngredient13": "Plum Sauce",
      "strIngredient14": "Soy Sauce",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 tablespoon",
      "strMeasure2": "1 lb",
      "strMeasure3": "1 clove peeled crushed",
      "strMeasure4": "1 tablespoon",
      "strMeasure5": "1 medium",
      "strMeasure6": "3 chopped",
      "strMeasure7": "3 Cups",
      "strMeasure8": "1 tablespoon",
      "strMeasure9": "1 tablespoon",
      "strMeasure10": "12",
      "strMeasure11": "For brushing",
      "strMeasure12": "To serve",
      "strMeasure13": "To serve",
      "strMeasure14": "To serve",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.simplyrecipes.com/recipes/air_fryer_chinese_egg_rolls/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-12-14 04:36:20"
    },
  ]
}

export default recipes